apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
- role: control-plane
  extraMounts:
    - containerPath: /etc/containerd/certs.d/docker.io/hosts.toml
      hostPath: containerd/certs.d/docker.io/hosts.toml
      readOnly: true
- role: worker
  extraMounts:
    - containerPath: /etc/containerd/certs.d/docker.io/hosts.toml
      hostPath: containerd/certs.d/docker.io/hosts.toml
      readOnly: true
- role: worker
  extraMounts:
    - containerPath: /etc/containerd/certs.d/docker.io/hosts.toml
      hostPath: containerd/certs.d/docker.io/hosts.toml
      readOnly: true
